Race.create(race: "Dwarf", size: "Medium", speed: 20, languages: "Common, Dwarven", senses: "Darkvision (60 feet)")
Race.create(race: "Elf", size: "Medium", speed: 30, languages: "Common, Elven", senses: "Low-light vision")
Race.create(race: "Gnome", size: "Small", speed: 20, languages: "Common, Gnome, Slyvan", senses: "Low-light vision")
Race.create(race: "Half-Elf", size: "Medium", speed: 30, languages: "Common, Elven", senses: "Low-light vision")
Race.create(race: "Halfling", size: "Small", speed: 20, languages: "Common, Halfling", senses: nil)
Race.create(race: "Half-Orc", size: "Medium", speed: 30, languages: "Common, Orc", senses: "Darkvision")
Race.create(race: "Human", size: "Medium", speed: 30, languages: "Common", senses: nil)

barbarian = Charclass.create(class_name: "Barbarian", hit_die: 12, skill_mod: 4, base_attack_bonus: 1)
bard = Charclass.create(class_name: "Bard", hit_die: 8, skill_mod: 6, base_attack_bonus: 0)
cleric = Charclass.create(class_name: "Cleric", hit_die: 8, skill_mod: 2, base_attack_bonus: 0)
druid = Charclass.create(class_name: "Druid", hit_die: 8, skill_mod: 4, base_attack_bonus: 0)
fighter = Charclass.create(class_name: "Fighter", hit_die: 10, skill_mod: 2, base_attack_bonus: 1)
monk = Charclass.create(class_name: "Monk", hit_die: 8, skill_mod: 4, base_attack_bonus: 0)
paladin = Charclass.create(class_name: "Paladin", hit_die: 10, skill_mod: 2, base_attack_bonus: 1)
ranger = Charclass.create(class_name: "Ranger", hit_die: 10, skill_mod: 6, base_attack_bonus: 1)
rogue = Charclass.create(class_name: "Rogue", hit_die: 8, skill_mod: 8, base_attack_bonus: 0)
sorceror = Charclass.create(class_name: "Sorceror", hit_die: 6, skill_mod: 2, base_attack_bonus: 0)
wizard = Charclass.create(class_name: "Wizard", hit_die: 6, skill_mod: 2, base_attack_bonus: 0)

acrobatics = Skill.create(skill_name: "Acrobatics", primary_attribute: "DEX")
appraise = Skill.create(skill_name: "Appraise", primary_attribute: "INT")
bluff = Skill.create(skill_name: "Bluff", primary_attribute: "CHA")
climb = Skill.create(skill_name: "Climb", primary_attribute: "STR")
craft = Skill.create(skill_name: "Craft", primary_attribute: "INT")
diplomacy = Skill.create(skill_name: "Diplomacy", primary_attribute: "CHA")
disdevice = Skill.create(skill_name: "Disable Device", primary_attribute: "DEX")
disguise = Skill.create(skill_name: "Disguise", primary_attribute: "CHA")
escartist = Skill.create(skill_name: "Escape Artist", primary_attribute: "DEX")
fly = Skill.create(skill_name: "Fly", primary_attribute: "DEX")
hananimal = Skill.create(skill_name: "Handle Animal", primary_attribute: "CHA")
heal = Skill.create(skill_name: "Heal", primary_attribute: "WIS")
intimidate = Skill.create(skill_name: "Intimidate", primary_attribute: "CHA")
karcana = Skill.create(skill_name: "Knowledge (Arcana)", primary_attribute: "")
kdungeon = Skill.create(skill_name: "Knowledge (Dungeoneering)", primary_attribute: "INT")
kengine = Skill.create(skill_name: "Knowledge (Engineering)", primary_attribute: "INT")
kgeo = Skill.create(skill_name: "Knowledge (Geography)", primary_attribute: "INT")
khist = Skill.create(skill_name: "Knowledge (History)", primary_attribute: "INT")
klocal = Skill.create(skill_name: "Knowledge (Local)", primary_attribute: "INT")
knature = Skill.create(skill_name: "Knowledge (Nature)", primary_attribute: "INT")
knoble = Skill.create(skill_name: "Knowledge (Nobility)", primary_attribute: "INT")
kplane = Skill.create(skill_name: "Knowledge (Planes)", primary_attribute: "INT")
kreli = Skill.create(skill_name: "Knowledge (Religion)", primary_attribute: "INT")
lingustics = Skill.create(skill_name: "Linguistics", primary_attribute: "INT")
perception = Skill.create(skill_name: "Perception", primary_attribute: "WIS")
perform = Skill.create(skill_name: "Perform", primary_attribute: "CHA")
profession = Skill.create(skill_name: "Profession", primary_attribute: "WIS")
ride = Skill.create(skill_name: "Ride", primary_attribute: "DEX")
senmotive = Skill.create(skill_name: "Sense Motive", primary_attribute: "WIS")
slohand = Skill.create(skill_name: "Sleight of Hand", primary_attribute: "DEX")
spellcraft = Skill.create(skill_name: "Spellcraft", primary_attribute: "INT")
stealth = Skill.create(skill_name: "Stealth", primary_attribute: "DEX")
survival = Skill.create(skill_name: "Survival", primary_attribute: "WIS")
swim = Skill.create(skill_name: "Swim", primary_attribute: "STR")
usmdevice = Skill.create(skill_name: "Use Magic Device", primary_attribute: "CHA")

CharclassSkill.create(charclass: barbarian, skill: acrobatics)
CharclassSkill.create(charclass: barbarian, skill: climb)
CharclassSkill.create(charclass: barbarian, skill: craft)
CharclassSkill.create(charclass: barbarian, skill: hananimal)
CharclassSkill.create(charclass: barbarian, skill: intimidate)
CharclassSkill.create(charclass: barbarian, skill: knature)
CharclassSkill.create(charclass: barbarian, skill: perception)
CharclassSkill.create(charclass: barbarian, skill: ride)
CharclassSkill.create(charclass: barbarian, skill: survival)
CharclassSkill.create(charclass: barbarian, skill: swim)
CharclassSkill.create(charclass: bard, skill: acrobatics)
CharclassSkill.create(charclass: bard, skill: appraise)
CharclassSkill.create(charclass: bard, skill: bluff)
CharclassSkill.create(charclass: bard, skill: climb)
CharclassSkill.create(charclass: bard, skill: diplomacy)
CharclassSkill.create(charclass: bard, skill: disguise)
CharclassSkill.create(charclass: bard, skill: escartist)
CharclassSkill.create(charclass: bard, skill: intimidate)
CharclassSkill.create(charclass: bard, skill: knature)
CharclassSkill.create(charclass: bard, skill: kreli)
CharclassSkill.create(charclass: bard, skill: kplane)
CharclassSkill.create(charclass: bard, skill: knoble)
CharclassSkill.create(charclass: bard, skill: klocal)
CharclassSkill.create(charclass: bard, skill: khist)
CharclassSkill.create(charclass: bard, skill: kgeo)
CharclassSkill.create(charclass: bard, skill: kengine)
CharclassSkill.create(charclass: bard, skill: kdungeon)
CharclassSkill.create(charclass: bard, skill: karcana)
CharclassSkill.create(charclass: bard, skill: lingustics)
CharclassSkill.create(charclass: bard, skill: perception)
CharclassSkill.create(charclass: bard, skill: perform)
CharclassSkill.create(charclass: bard, skill: profession)
CharclassSkill.create(charclass: bard, skill: senmotive)
CharclassSkill.create(charclass: bard, skill: slohand)
CharclassSkill.create(charclass: bard, skill: spellcraft)
CharclassSkill.create(charclass: bard, skill: stealth)
CharclassSkill.create(charclass: bard, skill: usmdevice)
CharclassSkill.create(charclass: cleric, skill: appraise)
CharclassSkill.create(charclass: cleric, skill: craft)
CharclassSkill.create(charclass: cleric, skill: diplomacy)
CharclassSkill.create(charclass: cleric, skill: heal)
CharclassSkill.create(charclass: cleric, skill: karcana)
CharclassSkill.create(charclass: cleric, skill: khist)
CharclassSkill.create(charclass: cleric, skill: knoble)
CharclassSkill.create(charclass: cleric, skill: kplane)
CharclassSkill.create(charclass: cleric, skill: kreli)
CharclassSkill.create(charclass: cleric, skill: lingustics)
CharclassSkill.create(charclass: cleric, skill: profession)
CharclassSkill.create(charclass: cleric, skill: senmotive)
CharclassSkill.create(charclass: cleric, skill: spellcraft)
CharclassSkill.create(charclass: druid, skill: climb)
CharclassSkill.create(charclass: druid, skill: craft)
CharclassSkill.create(charclass: druid, skill: fly)
CharclassSkill.create(charclass: druid, skill: hananimal)
CharclassSkill.create(charclass: druid, skill: heal)
CharclassSkill.create(charclass: druid, skill: kgeo)
CharclassSkill.create(charclass: druid, skill: knature)
CharclassSkill.create(charclass: druid, skill: perception)
CharclassSkill.create(charclass: druid, skill: profession)
CharclassSkill.create(charclass: druid, skill: ride)
CharclassSkill.create(charclass: druid, skill: spellcraft)
CharclassSkill.create(charclass: druid, skill: survival)
CharclassSkill.create(charclass: druid, skill: swim)
CharclassSkill.create(charclass: fighter, skill: climb)
CharclassSkill.create(charclass: fighter, skill: craft)
CharclassSkill.create(charclass: fighter, skill: hananimal)
CharclassSkill.create(charclass: fighter, skill: intimidate)
CharclassSkill.create(charclass: fighter, skill: kdungeon)
CharclassSkill.create(charclass: fighter, skill: kengine)
CharclassSkill.create(charclass: fighter, skill: profession)
CharclassSkill.create(charclass: fighter, skill: ride)
CharclassSkill.create(charclass: fighter, skill: survival)
CharclassSkill.create(charclass: fighter, skill: swim)
CharclassSkill.create(charclass: monk, skill: acrobatics)
CharclassSkill.create(charclass: monk, skill: climb)
CharclassSkill.create(charclass: monk, skill: craft)
CharclassSkill.create(charclass: monk, skill: escartist)
CharclassSkill.create(charclass: monk, skill: intimidate)
CharclassSkill.create(charclass: monk, skill: khist)
CharclassSkill.create(charclass: monk, skill: kreli)
CharclassSkill.create(charclass: monk, skill: perception)
CharclassSkill.create(charclass: monk, skill: perform)
CharclassSkill.create(charclass: monk, skill: profession)
CharclassSkill.create(charclass: monk, skill: ride)
CharclassSkill.create(charclass: monk, skill: senmotive)
CharclassSkill.create(charclass: monk, skill: stealth)
CharclassSkill.create(charclass: monk, skill: swim)
CharclassSkill.create(charclass: paladin, skill: craft)
CharclassSkill.create(charclass: paladin, skill: diplomacy)
CharclassSkill.create(charclass: paladin, skill: hananimal)
CharclassSkill.create(charclass: paladin, skill: heal)
CharclassSkill.create(charclass: paladin, skill: knoble)
CharclassSkill.create(charclass: paladin, skill: kreli)
CharclassSkill.create(charclass: paladin, skill: profession)
CharclassSkill.create(charclass: paladin, skill: ride)
CharclassSkill.create(charclass: paladin, skill: senmotive)
CharclassSkill.create(charclass: paladin, skill: spellcraft)
CharclassSkill.create(charclass: ranger, skill: climb)
CharclassSkill.create(charclass: ranger, skill: craft)
CharclassSkill.create(charclass: ranger, skill: hananimal)
CharclassSkill.create(charclass: ranger, skill: heal)
CharclassSkill.create(charclass: ranger, skill: intimidate)
CharclassSkill.create(charclass: ranger, skill: kdungeon)
CharclassSkill.create(charclass: ranger, skill: kgeo)
CharclassSkill.create(charclass: ranger, skill: knature)
CharclassSkill.create(charclass: ranger, skill: perception)
CharclassSkill.create(charclass: ranger, skill: profession)
CharclassSkill.create(charclass: ranger, skill: ride)
CharclassSkill.create(charclass: ranger, skill: spellcraft)
CharclassSkill.create(charclass: ranger, skill: stealth)
CharclassSkill.create(charclass: ranger, skill: survival)
CharclassSkill.create(charclass: ranger, skill: swim)
CharclassSkill.create(charclass: rogue, skill: acrobatics)
CharclassSkill.create(charclass: rogue, skill: appraise)
CharclassSkill.create(charclass: rogue, skill: bluff)
CharclassSkill.create(charclass: rogue, skill: climb)
CharclassSkill.create(charclass: rogue, skill: craft)
CharclassSkill.create(charclass: rogue, skill: diplomacy)
CharclassSkill.create(charclass: rogue, skill: disdevice)
CharclassSkill.create(charclass: rogue, skill: disguise)
CharclassSkill.create(charclass: rogue, skill: escartist)
CharclassSkill.create(charclass: rogue, skill: intimidate)
CharclassSkill.create(charclass: rogue, skill: kdungeon)
CharclassSkill.create(charclass: rogue, skill: klocal)
CharclassSkill.create(charclass: rogue, skill: lingustics)
CharclassSkill.create(charclass: rogue, skill: perception)
CharclassSkill.create(charclass: rogue, skill: perform)
CharclassSkill.create(charclass: rogue, skill: profession)
CharclassSkill.create(charclass: rogue, skill: senmotive)
CharclassSkill.create(charclass: rogue, skill: slohand)
CharclassSkill.create(charclass: rogue, skill: stealth)
CharclassSkill.create(charclass: rogue, skill: swim)
CharclassSkill.create(charclass: rogue, skill: usmdevice)
CharclassSkill.create(charclass: sorceror, skill: appraise)
CharclassSkill.create(charclass: sorceror, skill: bluff)
CharclassSkill.create(charclass: sorceror, skill: craft)
CharclassSkill.create(charclass: sorceror, skill: fly)
CharclassSkill.create(charclass: sorceror, skill: intimidate)
CharclassSkill.create(charclass: sorceror, skill: karcana)
CharclassSkill.create(charclass: sorceror, skill: profession)
CharclassSkill.create(charclass: sorceror, skill: spellcraft)
CharclassSkill.create(charclass: sorceror, skill: usmdevice)
CharclassSkill.create(charclass: wizard, skill: karcana)
CharclassSkill.create(charclass: wizard, skill: kdungeon)
CharclassSkill.create(charclass: wizard, skill: klocal)
CharclassSkill.create(charclass: wizard, skill: kreli)
CharclassSkill.create(charclass: wizard, skill: knature)
CharclassSkill.create(charclass: wizard, skill: kgeo)
CharclassSkill.create(charclass: wizard, skill: knoble)
CharclassSkill.create(charclass: wizard, skill: khist)
CharclassSkill.create(charclass: wizard, skill: kengine)
CharclassSkill.create(charclass: wizard, skill: kplane)
CharclassSkill.create(charclass: wizard, skill: appraise)
CharclassSkill.create(charclass: wizard, skill: craft)
CharclassSkill.create(charclass: wizard, skill: fly)
CharclassSkill.create(charclass: wizard, skill: lingustics)
CharclassSkill.create(charclass: wizard, skill: profession)
CharclassSkill.create(charclass: wizard, skill: spellcraft)
